# Generated by Django 4.1.2 on 2022-10-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100)),
                ('definition', models.CharField(blank=True, max_length=10000)),
                ('prefLabel', models.CharField(blank=True, max_length=100)),
                ('nieuwe_definitie', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='DefinitionToHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(blank=True, max_length=100)),
                ('html', models.CharField(blank=True, max_length=10000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitionToHtml', to='main.concept')),
            ],
        ),
    ]
