# Generated by Django 4.1.2 on 2022-10-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedConcepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100)),
                ('definition', models.CharField(blank=True, max_length=10000)),
                ('prefLabel', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DefinitionToHtml',
        ),
    ]
