# Generated by Django 4.1.2 on 2022-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_uploadedconcepts_uploadedconcept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100)),
                ('bevatLabel', models.CharField(blank=True, max_length=100)),
                ('opBeginPositie', models.IntegerField(max_length=10)),
                ('vanLengte', models.IntegerField(max_length=10)),
            ],
        ),
    ]
