# Generated by Django 4.1.2 on 2022-10-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_nieuwe_definitie_concept_definitionnohtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='definitionHtml',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
