# Generated by Django 4.1.2 on 2022-10-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_concept_definitionhtml'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
