# Generated by Django 4.1.2 on 2022-11-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
