# Generated by Django 4.1.2 on 2022-12-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_concept_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='related',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
