# Generated by Django 4.1.2 on 2022-12-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_concept_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='related',
        ),
        migrations.AddField(
            model_name='uploadedconcept',
            name='related',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
