# Generated by Django 4.1.2 on 2023-01-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_concept_related_uploadedconcept_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='definition',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
